import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/ProductPage.module.css'
import Link from 'next/link';
import { motion } from 'framer-motion'
import { useState, useEffect } from 'react';




export default function ProductPage({ product }) {
    const [screenWidth, setScreenWidth] = useState(0)
    const [isMobile, setIsMobile] = useState(false)
    const [activeImage, setActiveImage] = useState('')

    

     
    useEffect(() => {
      function watchWidth()  {     
       setScreenWidth(window.innerWidth)
      }

      window.addEventListener("resize", watchWidth)
      watchWidth()
     
   }, [])

   useEffect(() => {

       function mobileScreen() {
           if (screenWidth < 690)  {
               setIsMobile(true)
               
          
            }   else {
               setIsMobile(false)
               
           }
       }

       mobileScreen()

   }, [screenWidth])

   
    console.log(product)

    const handleImage = (image) => {
      setActiveImage(image)
      console.log(activeImage)
    }

    const formattedPrice = new Intl.NumberFormat('en-US', {
        style: 'currency',
        currency: 'USD',
      });


    // to abstaract it out
      const addToCart = async () => {

        let localCartData = JSON.parse(
          window.localStorage.getItem('koopiBlock:shopify:cart')

        
        );

        if (!localCartData.cartId) {
          console.error('woops there was an error loading zi cart')
          return
        }

        console.log(localCartData.cartId)
        console.log(product.variantId)

         const result = await fetch(`http://localhost:3000/api/add-to-cart?cartId=${localCartData.cartId}&variantId=${product.variantId}`, {
           method: 'POST', 
         })

         console.log(result)

         if (!result.ok) {
           console.error('There was a problem adding the item to the cart');
           return;
         }

         window.localStorage.setItem('koopiBlock:shopify:status', 'dirty')

    }

    function ProductDisplay({slug, imageSrc, imageAlt, title, description, price, images }) {

      const formattedPrice = new Intl.NumberFormat('en-US', {
      style: 'currency',
      currency: 'USD',
    });

    console.log(images)
  
    return (
      <div className={styles.productSec}>
        <div className={styles.productImgs}>         
            <div className={styles.imagesConatiner}>
              <div className={styles.mainImageCont}>
                <Image 
                    src={activeImage ? (activeImage) : (imageSrc)}
                    alt={activeImage ? (activeImage) : (imageSrc)}
                    width={isMobile ? 200 : 450}
                    height={isMobile ? 200 : 450}
                    className={styles.mainImage}
                    />
              </div>
              <div className={styles.tinyImagesCont}>
                {images.map((image, i) => (
                  <div className={styles.tinyImage} key={i}>
                    <Image 
                      src={image.node.src}
                      alt={image.node.src}
                      width={isMobile ? 50 : 150}
                      height={isMobile ? 50 : 150}
                      onClick={() => handleImage(image.node.src)}
                    />           
                  </div>
                ))}
              </div>
            </div>
        </div>
        <div className={styles.productCont}>
          <h2 className={styles.productTitle}>{title}</h2>
          <p className={styles.productDesc}>{description}</p>
          <p className={styles.productPrice}>{formattedPrice.format(price)}</p>
          <div className={styles.ctaContainer}>
            <motion.p className={styles.ctaLink2} onClick={addToCart}
              whileTap={{ scale: 0.9 }}
              whileHover={{ scale: 1.2 }}                        
            >
              קנה עכשיו
            </motion.p>
            <motion.p className={styles.ctaLink} onClick={addToCart}
              whileTap={{ scale: 0.9 }}
              whileHover={{ scale: 1.2 }}                        
            >
              הוסף לסלסלה
            </motion.p>
          </div>
        </div>     
      </div>
    );
  }

    
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description"
                    content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>

                <div className={styles.products}>
                    <ProductDisplay {...product} />
                </div>
            </main>
        </div>
    )
}

export async function getStaticPaths() {

    const url = new URL(process.env.URL || 'http://localhost:3000');
    url.pathname = '/api/product';
   

    const res = await fetch(url.toString());
    
    if (!res.ok) {
        console.error(res);
        return { props: {} };
    }

    const data = await res.json();

    return {
        paths: data.products.edges.map(({ node }) => `/product/${node.handle}`),
        fallback: true,

    }
}

export async function getStaticProps({ params }) {
    const url = new URL(process.env.URL || 'http://localhost:3000');
    url.pathname = '/api/product';

    const res = await fetch(url.toString());

    if (!res.ok) {
        console.error(res);
        return { props: {} };
    }

    const data = await res.json();


    const product = data.products.edges

        .map(({ node }) => {

            if (node.totalInvetory <= 0) {
                return false;
            }
            return {
                id: node.id,
                title: node.title,
                description: node.description,
                images: node.images.edges,
                imageSrc: node.images.edges[0].node.src,
                imageAlt: node.title,
                price: node.variants.edges[0].node.priceV2.amount,
                slug: node.handle,
                variantId: node.variants.edges[0].node.id
            }
        })
        .find(({ slug }) => slug === params.slug)


    return {
        props: { product },
    }
}




